<?=$this->partial('_partials/mensajes.phtml',array('messages' => $this->messages,'tipoMessages' => $this->tipoMessages));?>
<div class="widget-box">
    <div class="widget-title">	
        <h5><?=$this->active?></h5>
    </div>
<div class="widget-content nopadding">
    <table id='tabla' class="table table-condensed table-bordered" >
        <thead>
        <tr><th></th><th>Nombres</th><th>Celular</th><th>Correo</th><th>Mensaje</th><th>Respuesta</th><th>Fecha_envio</th><th>Respondido</th></tr>
        </thead>
        <?php
        echo '<tbody>';
        foreach ($this->data as $value) {
            $estado = 'checkmark.png';
            echo '<tr>';
            echo '<td width=5% class="taskOptions">';
            if ($value['respondido'] == 0) {
            echo '<a data-original-title="Responder" class="tip-top" href="#myModal" data-toggle="modal" onclick="enviarCorreo('.$value['id'].')">';
            echo '<i class="icon-envelope"></i></a>&nbsp;&nbsp;';
            }
            echo '</td>';
        ?>   
        <?php 
	echo "<td>".$value['nombres']."</td>";
	echo "<td>".$value['celular']."</td>";
	echo "<td>".$value['correo']."</td>";
	echo "<td>".$value['mensaje']."</td>";
        echo "<td>".$value['respuesta']."</td>";
	echo "<td>".$this->FechaMostrar($value['fecha_envio'])."</td>";
        $respondido = 'Sí';
        if ($value['respondido'] == 0)
            $respondido = 'No';
	echo "<td class='taskOptions'>".$respondido."</td>";
	echo "</tr>";
	?>
        <?php
        }
        echo '</tbody>';
        ?>
    </table>
</div>
</div>    
<?=$this->partial('_partials/modal.phtml',array('model' => $this->model));?>