<?=$this->partial('_partials/mensajes.phtml',array('messages' => $this->messages,'tipoMessages' => $this->tipoMessages));?>
<div class="widget-box">
    <div class="widget-title">	
        <h5><?=$this->active?></h5>
    </div>
<div class="widget-content nopadding">
    <table id='tabla' class="table table-condensed table-bordered" >
        <thead>
        <tr><th></th><th>Nom_prod</th><th>Precio</th><th>Imagen</th><th>Estado</th><th>Usuario_crea</th><th>Fecha_crea</th><th>Usuario_actu</th><th>Fecha_actu</th><th>Id_categoria</th><th>Codigo_web</th></tr>
        </thead>
        <?php
        echo '<tbody>';
        foreach ($this->data as $value) {
            $estado = 'checkmark.png';
            echo '<tr>';
            echo '<td width=5% class="taskOptions">';
            echo '<a data-original-title="Editar" class="tip-top" href="#myModal" data-toggle="modal" onclick="editar('.$value['id'].')">';
            echo '<i class="icon-pencil"></i></a>&nbsp;&nbsp;';
            echo '<a data-original-title="Eliminar" class="tip-top" href="#myModal" data-toggle="modal" onclick="elimina('.$value['id'].')">';
            echo '<i class="icon-trash"></i></a>';
            echo '</td>';
        ?>   
        <?php 
	echo "<td>".$value['nom_prod']."</td>";
	echo "<td>".$value['precio']."</td>";
	echo "<td>".$value['imagen']."</td>";
	echo "<td>".$value['estado']."</td>";
	echo "<td>".$value['usuario_crea']."</td>";
	echo "<td>".$this->FechaMostrar($value['fecha_crea'])."</td>";
	echo "<td>".$value['usuario_actu']."</td>";
	echo "<td>".$this->FechaMostrar($value['fecha_actu'])."</td>";
	echo "<td>".$value['id_categoria']."</td>";
	echo "<td>".$value['codigo_web']."</td>";
	echo "</tr>";
	?>
        <?php
        }
        echo '</tbody>';
        ?>
    </table>
</div>
</div>    
<?=$this->partial('_partials/modal.phtml',array('model' => $this->model));?>