<style>
.zend_form input[type=text], 
.zend_form input[type=password]
{ width:200px; }
.zend_form textarea{ width: 300px; height:100px; }
.zend_form .line{ margin:10px 0; display: block; clear: both;}
.zend_form .line dt, .zend_form .line dd{ display:inline-block; vertical-align:middle; }
.zend_form .line dt, .zend_form .line dd{ float:left;width:500px }
.zend_form .line dt{ width:200px; }
.zend_form ul.errors{ display:inline; margin:0; padding:0; list-style:none }
.zend_form ul.errors li{ margin:0; padding:0 }
#form-contacto ul.errors li {float:right;height:20px;width: 280px;color:#CC0000;}
</style>
<script>
$(document).ready(function(){
  $("#celular").numeric({"negative":false,"decimal":false});
})
</script>
<div class="breadcrumb">
    <a href="<?php echo SITE_URL ?>" title="Volver al Inicio">Inicio</a><span class="navigation-pipe">&gt;</span><span class="navigation_page">Contacto</span>
</div>
<h2>Contactar con nosotros</h2>
	<p class="bold">Para preguntas relacionadas con un pedido o para informarse sobre nuestros productos.</p>
        <span style="color: red"><?=$this->mensaje?></span>
        <fieldset>
		<h3>Enviar un mensaje</h3>
                <?php echo $this->form; ?>
                <br>
	</fieldset>
<br /><br />


