<ul id="lstProducto">
<?php
foreach ($this->productos as $productos)
{
    $imagen = SITE_URL."/images/small/".$productos["imagen"];
    $imagenLarge = SITE_URL."/images/large/".$productos["imagen"];
    echo '<li class="ajax_block_product"><a href='.$imagenLarge.' title="'.$productos["nom_prod"].'"  class="thickbox" rel="gallery-plants"><img src="'.$imagen.'" alt="'.$productos["nom_prod"].'">';
    echo '</a><h5><center><a href="" title="'.$productos["nom_prod"].'" >'.substr($productos["nom_prod"],0,60).'</a><center></h5>';
    echo '<span class="price">Precio: s/ '.$productos["precio"].' <font size=7>('.$productos["codigo_web"].')</font></span>';
    echo '<p align=center><a class="exclusive_link"  href="'.SITE_URL.'/producto/'.$productos["id"].'" title="Añadir al carrito"><img src="'.SITE_URL.'/images/icons/addcarrito.jpg"></a>';
    echo '</p></li>';
 }
 ?>    		   
 </ul>