<div id="footer_wrapper">
	<div id="footer">
<ul class="block_various_links" id="block_various_links_footer">
	<li class="first_item"><a href="" title="">Especiales</a></li>
	<li class="item"><a href="" title="">Nuevos productos</a></li>
	<li class="item"><a href="" title="">Top ventas</a></li>
	<li class="item"><a href="<?php echo $this->staticUrl."/contacto"; ?>" title="">Contacte con nosotros</a></li>
	<li class="last_item">©2012 Desarrollado por <a href="mailto:martin.programmer@gmail.com">Martin Grados</a></li>
</ul>
<div id="currencies_block_top">
<img src="<?php echo SITE_URL."/img/PayPal.gif";?>">
    
</div>
</div>
</div>
</body>