<!DOCTYPE HTML>
<html>
<head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>Florería Don Lucho</title>
	<meta name="description" content="Flores, arreglos florales, rosas">
	<meta name="keywords" content="flores, rosas">
	<meta name="robots" content="index,follow">
        <link rel="icon" type="image/vnd.microsoft.icon" href="<?php echo SITE_URL."/img/favicon.ico";?>"  />
	<link rel="shortcut icon" type="image/x-icon" href="<?php echo SITE_URL."/img/favicon.ico";?>" />
	<link href="<?php echo SITE_URL."/css/global.css"; ?>" rel="stylesheet" type="text/css" media="all">
	<script type="text/javascript" async="" src="<?php echo SITE_URL."/js/plugins/ga.js"; ?>"></script>
        <script type="text/javascript" src="<?php echo SITE_URL."/js/plugins/tools.js"; ?>"></script>
	<script type="text/javascript">
		var baseDir = 'http://livedemo00.template-help.com/prestashop_33137/';
		var static_token = '222fd4897b5e5f038295d390faf62611';
		var token = '8deb17699c48962a96f2aa737aa5d003';
		var priceDisplayPrecision = 2;
		var roundMode = 2;
	</script>
        <script type="text/javascript" src="<?php echo SITE_URL."/js/plugins/jquery-1.4.3.min.js"; ?>" ></script>
	<script type="text/javascript" src="<?php echo SITE_URL."/js/plugins/jquery-1.2.6.pack.js"; ?>" ></script>
	<script type="text/javascript" src="<?php echo SITE_URL."/js/plugins/jquery.easing.1.3.js"; ?>"></script>
	<script type="text/javascript" src="<?php echo SITE_URL."/js/plugins/jquery.hotkeys-0.7.8-packed.js"; ?>" ></script>
        <link rel="stylesheet" type="text/css" href="<?php echo SITE_URL."/js/plugins/jquery.autocomplete.css"; ?>" >
        <script type="text/javascript" src="<?php echo SITE_URL."/js/plugins/jquery.autocomplete.js";?>"></script>
        <script type="text/javascript" src="<?php echo SITE_URL."/js/web/inicio.js";?>"></script>
        <script type="text/javascript" src="<?php echo SITE_URL."/js/plugins/jquery.thickBox.js";?>"></script>
        <link rel="stylesheet" type="text/css" href="<?php echo SITE_URL."/css/tichkbox.css"; ?>">
        <link rel="stylesheet" type="text/css" href="<?php echo SITE_URL."/css/login_web.css"; ?>">
        <?php echo $this->headLink() . "\n" ?><?php echo $this->headScript() . "\n" ?>
        <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-44936957-1', 'floreriadonlucho.com');
        ga('send', 'pageview');

       </script>
</head>
<body id="index">
<div id="wrapper1">
<div id="wrapper2">
		<div id="header">
			<h1 id="logo"><a href="" title="Florería Don Lucho"><img src="<?php echo SITE_URL."/img/logo.png";?>" alt="Flower"></a></h1>
			<div id="header_right">
<div id="header_user" >
	<ul>
		<li id="shopping_cart">
                        <a href="http://www.facebook.com/FloreriaDonLucho?ref=hl">
			<img src="<?=SITE_URL."/images/icons/facebook.png"?>" width="10%" alt="Facebook Florería Don Lucho" >
                        </a>
			<a href="#" title="Su carrito de la compra">Carrito:</a>
			<div>
				<span class="ajax_cart_quantity hidden">0</span>
				<span class="ajax_cart_product_txt hidden">producto</span>
				<span class="ajax_cart_product_txt_s hidden">productos</span>
				<span class="ajax_cart_no_product">vacío</span>
			</div>
                </li>
		<li id="header_user_info">
                    <?php $auth = Zend_Auth::getInstance()->hasIdentity();
                    if ($auth)
                        echo 'Mi cuenta';
                    else { ?> 
                    <?=$this->partial('_partials/_login_web.phtml');?>
                    <?php } ?>
		</li>
                
	</ul>
</div>
<ul id="header_links" >
	<li id="header_link_home">
		<a class="active" href="<?php echo SITE_URL; ?>" title="inicio">inicio</a>
	</li>
	<li id="header_link_specials">
		<a href="#" title="especiales">especiales</a>
	</li>
	<li id="header_link_sitemap">
		<a href="<?php echo SITE_URL."/registro"; ?>" title="Regístrate">Regístrate</a>
	</li>
	<li id="header_link_contact">
		<a href="<?php echo SITE_URL."/contacto"; ?>" title="contacto">contacto</a>
	</li>
</ul>
<div id="search_block_top">
	<label for="search_query">Buscar producto: </label>
	<form method="post" action="/producto/buscar" onsubmit="return validaBusqueda();" id="searchbox">
            <input type="text" id="search_query" name="search" autocomplete="off"  class="ac_input">
		<a  style="cursor: pointer" onclick="validaBusqueda();">Ir</a>
	</form>
</div>
	<script type="text/javascript">
		
		function formatSearch(row) {
			return row[2] + ' > ' + row[1];
		}

		function redirectSearch(event, data, formatted) {
			$('#search_query').val(data[1]);
			document.location.href = data[3];
		}
	
	</script>

			</div>
		</div>
		<div id="columns">
			<!-- Left -->
			<div id="left_column" class="column">
				<script type="text/javascript" src="<?php echo SITE_URL."/js/plugins/treeManagement.js";?>"></script>

<!-- Block categories module -->
<div id="categories_block_left" class="block">
	<h4>Categorías</h4>
	<div class="block_content">
		<ul class="tree dynamized" style="display: block; " id="lstCategoria">
                    <?php
                    if ($this->layout()->categoria != null) {
                        foreach ($this->layout()->categoria as $reg) {
                            $nomCat = str_replace(' ', '-', strtolower($reg["nom_cat"]));
                            echo "<li><a href=/categoria/".$nomCat.'-'.$reg['id'].">".$reg["nom_cat"]."</a></li>";
                        }
                            
                    }
                    ?>
                </ul>
	</div>
</div>
<script type="text/javascript">
	$('div#categories_block_left ul.dhtml').hide();
</script>
<script type="text/javascript" src="<?php echo SITE_URL."/js/plugins/iutil.prestashop-modifications.js";?>"></script>
<script type="text/javascript" src="<?php echo SITE_URL."/js/plugins/ifxtransfer.js"; ?>"></script>
<script type="text/javascript">
var CUSTOMIZE_TEXTFIELD = 1;
var customizationIdMessage = 'Personalización n°';
var removingLinkText = 'eliminar este producto de mi carrito';
</script>
<script type="text/javascript" src="<?php echo SITE_URL."/js/plugins/ajax-cart.js"; ?>"></script>
<div id="cart_block" class="block exclusive">
	<h4>
		<a href="">Carrito</a>
				<span id="block_cart_expand" class="hidden">&nbsp;</span>
		<span id="block_cart_collapse">&nbsp;</span>
			</h4>
	<div class="block_content">
	<div id="cart_block_summary" class="collapsed">
				<span class="ajax_cart_product_txt_s hidden">productos</span>
		<span class="ajax_cart_product_txt hidden">producto</span>
				<span class="ajax_cart_no_product">(vacío)</span>	</div>
	<div id="cart_block_list" class="expanded">
			<p id="cart_block_no_products">Sin producto</p>
				<div class="cart-prices">
                                <div class="cart-prices-block">
				<span>Total</span>
				<span id="cart_block_total" class="price ajax_block_cart_total">s/ 0.00</span>
			</div>
		</div>

						<p id="cart-buttons">
                                                    <a href="<?=SITE_URL."/carrito"?>" class="exclusive" title="Carrito">Carrito</a>
			<a href="" id="button_order_cart" class="button" title="Confirmar">Confirmar</a>
		</p>
	</div>
	</div>
</div>
<iframe src="http://www.facebook.com/plugins/recommendations.php?site=http%3A%2F%2Fwww.floreriadonlucho.com&amp;width=150&amp;height=300&amp;header=true&amp;colorscheme=light" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:150px; height:300px;" allowTransparency="true"></iframe>
			</div>
			<!-- Center -->
<div id="center_column" class="center_column">
<script src="<?php echo SITE_URL."/js/plugins/jquery.dimensions.js";?>" type="text/javascript"></script>
<script src="<?php echo SITE_URL."/js/plugins/jquery.mousewheel.min.js";?>" type="text/javascript"></script>
<script src="<?php echo SITE_URL."/js/plugins/jScrollHorizontalPane.js";?>" type="text/javascript"></script>
<div class="holder">
	<div class="jScrollPaneContainer" style="height: 375px; width: 950px; "><div class="scroll-pane" id="pane5" style="height: 426px; width: auto; padding-right: 0px; position: absolute; overflow-x: visible; overflow-y: visible; left: 0px; ">
	<ul class="blocks">
					<li>
			<a href="" title="Signs of Summer Tulip Bouquet">
				<img src="<?php echo SITE_URL."/img/productos/9-25-slider.jpg"; ?>" alt="Signs of Summer Tulip Bouquet">
			</a>
		</li>
					<li>
			<a href="" title="Silver Linings Calla Lily Plant">
				<img src="<?php echo SITE_URL."/img/productos/10-28-slider.jpg"; ?>" alt="Silver Linings Calla Lily Plant">
			</a>
		</li>
					<li>
			<a href="" title="Simple Perfection Bouquet">
				<img src="<?php echo SITE_URL."/img/productos/11-31-slider.jpg"; ?>" alt="Simple Perfection Bouquet">
			</a>
		</li>
					<li>
			<a href="" title="Natural Wonders Bouquet">
				<img src="<?php echo SITE_URL."/img/productos/32-94-slider.jpg"; ?>" alt="Natural Wonders Bouquet">
			</a>
		</li>
					<li>
			<a href="" title="Stunning Beauty Bouquet">
				<img src="<?php echo SITE_URL."/img/productos/41-121-slider.jpg"; ?>" alt="Stunning Beauty Bouquet">
			</a>
		</li>
					<li>
			<a href="" title="Lavender Rose Bouquet">
				<img src="<?php echo SITE_URL."/img/productos/29-85-slider.jpg"; ?>" alt="Lavender Rose Bouquet">
			</a>
		</li>
					<li>
			<a href="" title="Sunshine&#39;s Promise Tulip Bouquet">
				<img src="<?php echo SITE_URL."/img/productos/48-142-slider.jpg"; ?>" alt="Sunshine&#39;s Promise Tulip Bouquet">
			</a>
		</li>
					<li>
			<a href="" title="Citrus Burst Bouquet">
				<img src="<?php echo SITE_URL."/img/productos/20-58-slider.jpg"; ?>" alt="Citrus Burst Bouquet">
			</a>
		</li>
					<li>
			<a href="" title="Pink Gerbera in a Jeweled Planter">
				<img src="<?php echo SITE_URL."/img/productos/4-10-slider.jpg"; ?>" alt="Pink Gerbera in a Jeweled Planter">
			</a>
		</li>
					<li>
			<a href="" title="Beauty Calla Lily Bouquet">
				<img src="<?php echo SITE_URL."/img/productos/13-37-slider.jpg"; ?>" alt="Beauty Calla Lily Bouquet">
			</a>
		</li>
					<li>
			<a href="" title="Sun-Drenched Summer Rose Bouquet">
				<img src="<?php echo SITE_URL."/img/productos/44-130-slider.jpg"; ?>" alt="Sun-Drenched Summer Rose Bouquet">
			</a>
		</li>
					<li>
			<a href="" title="Sweet Surprises Bouquet">
				<img src="<?php echo SITE_URL."/img/productos/51-151-slider.jpg"; ?>" alt="Sweet Surprises Bouquet">
			</a>
		</li>
					<li>
			<a href="" title="Rush of Color Assorted Tulip Bouquet">
				<img src="<?php echo SITE_URL."/img/productos/35-103-slider.jpg";?>" alt="Rush of Color Assorted Tulip Bouquet">
			</a>
		</li>
					<li>
			<a href="" title="Deep Emotions Bouquet">
				<img src="<?php echo SITE_URL."/img/productos/23-67-slider.jpg";?>" alt="Deep Emotions Bouquet">
			</a>
		</li>
					<li>
			<a href="" title="Tulips for Your Valentine">
				<img src="<?php echo SITE_URL."/img/productos/7-19-slider.jpg";?>" alt="Tulips for Your Valentine">
			</a>
		</li>
					<li>
			<a href="" title="Blooming Bounty Bouquet">
				<img src="<?php echo SITE_URL."/img/productos/16-46-slider.jpg";?>" alt="Blooming Bounty Bouquet">
			</a>
		</li>
					<li>
			<a href="" title="Sunny Sentiments Bouquet">
				<img src="<?php echo SITE_URL."/img/productos/46-136-slider.jpg";?>" alt="Sunny Sentiments Bouquet">
			</a>
		</li>
					<li>
			<a href="" title="Silver Linings Calla Lily Plant">
				<img src="<?php echo SITE_URL."/img/productos/37-109-slider.jpg";?>" alt="Silver Linings Calla Lily Plant">
			</a>
		</li>
					<li>
			<a href="" title="Breathtaking Beauty Bouquet">
				<img src="<?php echo SITE_URL."/img/productos/18-52-slider.jpg";?>" alt="Breathtaking Beauty Bouquet">
			</a>
		</li>
	<li class="carousel_last">
			<a href="" title="Eye-catching boxed floral arrangement typically including lilliums, iris, gerberas and roses">
				<img src="<?php echo SITE_URL."/img/productos/25-73-slider.jpg";?>" alt="Eye-catching boxed floral arrangement typically including lilliums, iris, gerberas and roses">
			</a>
		</li>


	
		</ul>
	</div><div class="jScrollPaneTrack"><div class="jScrollPaneDrag" style="width: 140.83957553058676px; left: 0px; "><div class="jScrollPaneDragLeft" style="height: 20px; "></div><div class="jScrollPaneDragRight" style="height: 20px; "></div></div></div></div>
</div>
<div id="featured-products_block_center" class="block products_block">
			<div class="block_content">
			<?php echo $this->layout()->content ?>
		</div>
</div>
<iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwww.floreriadonlucho.com&amp;layout=standard&amp;show_faces=true&amp;width=450&amp;action=like&amp;colorscheme=light&amp;height=80" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:80px;" allowTransparency="true"></iframe>
</div>
</div>
<br class="clear">
</div>
</div>
<?php echo $this->render("footer.phtml"); ?>
</html>