<table width="96%" style="margin: 10px 0px 0px 10px" align="center" border="0">
    <tr>
        <td align="center" style="font-weight:bold;"><span style="color:#656565;font-size:36px;">Su oferta de empleo para </span><br/><span 
style="color:#100F0F;font-size:40px;">"<?=$this->anuncioPuesto?>"</span><br /><span style="color:#656565;font-size:36px;">est&aacute; publicada en nuestra Bolsa</span></td>
    </tr>
    <tr>
        <td align="center" style="font-size: 15px;">Sus datos de acceso son: <br />
            <span style="font-weight:bold;">Usuario : </span><a style="color: #007FD2;text-decoration:none;" href="#"><?=$this->to?></a>
        </td>
    </tr>
    <tr><td height="5"></td></tr>
</table>

<table cellspacing="6" border="0" cellpadding="0" width="750">
    <tr>
        <td align="center">
            <table width="95%" cellspacing="5" border="0" cellpadding="2">
                <tr>
                    <td width="42%">
                        <table border="0" cellpadding="0" cellspacing="0" style="font-size:13px;">
                            <tr>
                                <td height="40">
                                    <?php if ($this->ver_aptitus == 1){ ?>
                                    Esta oferta tambi&eacute;n ha sido publicada en APTiTUS.pe<br/><br/>
                                    <?php } ?>
                                    Las caracter&iacute;sticas de la oferta son:<br/><br/>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <span style="font-weight:bold;">Puesto solicitado:</span> <?=$this->anuncioPuesto?><br/>
                                    <span style="font-weight:bold;">Empresa:</span> <?=$this->razonSocial?><br/>
                                    
                                    <?php if($this->ver_aptitus == 1) {?>
                                    <span style="font-weight:bold;">C&oacute;digo APTiTUS: </span><?=isset($this->codigo_adecsys_compra)? $this->codigo_adecsys_compra:$this->anuncioUrl?><br />
                                    <?php } ?>
                                    <span style="font-weight:bold;">Vigencia de la oferta de empleo: </span>del <?=$this->FriendlyDate($this->fechaPago)?> hasta <?=$this->FriendlyDate($this->anuncioFechaVencimiento)?><br />
                                    <?php if($this->ver_aptitus == 1) {?>
                                    <span style="font-weight:bold;">Vigencia del Proceso de Selecci&oacute;n en APTiTUS: </span>del <?=$this->FriendlyDate($this->fechaPago)?> hasta <?=$this->FriendlyDate($this->anuncioFechaVencimientoProceso)?><br />
                                    <?php } ?>
                                </td>
                            </tr>
		<tr><td width="48%" style="font-size:13px;"><br>
                        <a style="color: #007FD2;" href="<?=SITE_URL.$this->url(array('slug' => $this->anuncioSlug, 'url_id' => $this->anuncioUrl), 'aviso', true)?>">Ver oferta publicada</a>
                        &nbsp;&nbsp;&nbsp;<a style="color: #007FD2;" href="<?=SITE_URL.'/empresa/publica-aviso'?>">Publicar otra oferta</a>
                    </td></tr>
                        </table>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

<table style="border-left-color: #fff; border-top-color: #fff; border-bottom: #fff 1px solid; border-right-color: #fff" cellspacing="0" cellpadding="0" border="0">
    <tr>
        <td align="left" width="750" style="padding-left:10px;padding-bottom:10px;">
            <h1 style="padding-right: 0px; padding-left: 20px;font-weight: bold; font-size: 16px; margin: 0px; color: #222222; padding-top: 10px; padding-bottom: 10px;">
                <span style="font-family:Arial, Helvetica, sans-serif;">Le deseamos &eacute;xitos en la b&uacute;squeda de candidatos.</span><br />
                <span style="font-family:Arial, Helvetica, sans-serif;">&iexcl;Gracias por anunciar en nuestra Bolsa!</span><br /><br />
                <span style="color:#000;font-family: Arial, Helvetica, sans-serif">Bolsa de Empleos <?=$this->NombreInstitucion()?></span> 
            </h1> 
        </td>
    </tr>
</table>