 <table width="88%" style="margin: 10px 0px 0px 10px" align="center" border="0">
    <tr>
    <td colspan="2" height="10"></td>
    </tr>
    <tr>
        <td colspan="2" align="center" valign="top" style="font-weight:bold;padding-bottom:10px;">
            <span style="color:#100F0F;font-size:24px;">Su mensaje será atentido a la brevedad posible.
            </span>
        </td>
    </tr>
    <tr><td height="10" colspan="2"></td></tr>
    <tr>
    	<td colspan="2" align="left" style="font-size: 16px;">
                <span style="">Nombres : </span><?=$this->nombres?><br>
                <span style="">Correo : </span><a style="color: #007FD2;text-decoration:none;" href="#"><?=$this->to?></a><br>
                <span style="">Celular : </span><?=$this->celular?><br>
                <span style="">Su mensaje es: </span><?=$this->mensaje?><br>
        </td>
    </tr>
    <tr><td height="5" colspan="2"></td></tr>
</table>

<table style="border-left-color: #fff; border-top-color: #fff; border-bottom: #fff 1px solid; border-right-color: #fff" 
    cellspacing="0" cellpadding="0" border="0">
    <tr>
        <td align="center" width="750" style="padding-left:30px;padding-bottom:10px;">
            <h1 style="padding-right: 0px; padding-left: 20px;font-weight: bold; font-size: 18px; margin: 0px; color: #222222; padding-top: 10px; padding-bottom: 10px;">
                <span style="font-family:Arial, Helvetica, sans-serif;">&iexcl;Gracias por contactar con nosotros.!</span><br /><br />
                <span style="color:#000;font-family: Arial, Helvetica, sans-serif"><?=PAGINA_WEB?> </span> 
            </h1> 
        </td>
    </tr>
</table>