<div id="loginContainer">
    <a href="#" id="loginButton"><span>Entrar</span></a>
    <div id="loginBox">
        <form id="loginForm">
            <fieldset id="body">
                <fieldset>
                    <label for="email">Email:</label>
                    <input type="text" name="correo_web" id="correo_web" />
                </fieldset>
                <fieldset>
                    <label for="password">Contraseña</label>
                    <input type="password" name="clave_web" id="clave_web" />
                </fieldset>
                <input type="button" id="login" onclick="" value="Entrar" />
                <span style='color:#000000;font-size: 9pt' id="msjError"></span>
            </fieldset>
            <span><a href="#" class="forgetClave">¿Olvidaste tu contraseña?</a></span>
        </form>
    </div>
</div>
 <a id="your_account" href="#" title="Su cuenta">Su cuenta</a> 